spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: boot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: my-project-name-url-shortener-and-secret-key-for-authentication
  expiration: 3600000

